# Generated by Django 2.2 on 2019-04-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(verbose_name='posted Date'),
        ),
    ]
