# Generated by Django 2.2 on 2019-04-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sblog', '0002_auto_20190415_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
